"""deleted unique for guid

Revision ID: ffb5c6b36577
Revises: 
Create Date: 2021-09-14 13:17:08.345152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffb5c6b36577'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('guid', table_name='votes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('guid', 'votes', ['guid'], unique=False)
    # ### end Alembic commands ###
